Feature free purchase
vtex-apps/checkout-payment pull request #16
Opened 2020-11-16 16:55 UTC by pedromtec

#### What problem is this solving?

Same [here](https://github.com/vtex-apps/order-payment/pull/13)

#### How should this be manually tested?

Choose the account `pilateslovers`. 
[App Store](https://pedrocheckout--extensions.myvtex.com/vtex-facebook-pixel/p)

I'm getting some issues to test the flow using `checkoutio` account because I can't choose a free shipping.  
[Checkout IO](https://pedrocheckout--checkoutio.myvtex.com/Produto-gratis/p)

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [x] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Jira story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
✔️ | New feature 
_ | Breaking change 
_ | Technical improvements 

#### Related to / Depends on
[PR13](https://github.com/vtex-apps/order-payment/pull/13)

2020-11-17 12:21 UTC, lucasecdb approved these changes

2020-11-17 18:40 UTC, arturpimentel approved these changes

2021-01-07 18:21 UTC, lucasecdb requested changes

2021-01-07 18:21 UTC, lucasecdb commented on messages/pt.json
> +  "store/checkout-payment.freePurchase": "Tu compra es gratis"
```suggestion
  "store/checkout-payment.freePurchase": "Sua compra é gratuita"
```

2021-01-07 18:26 UTC, wdsrocha commented on messages/pt.json
> +  "store/checkout-payment.cardFormTitle": "Contéiner para o formulário de cartão de crédito",
```suggestion
  "store/checkout-payment.cardFormTitle": "Contêiner para o formulário de cartão de crédito",
```

2021-01-08 17:40 UTC, pedromtec commented on messages/pt.json
> +  "store/checkout-payment.freePurchase": "Tu compra es gratis"
Problems with rebase :/

2021-01-08 17:40 UTC, pedromtec commented on messages/pt.json
> +  "store/checkout-payment.cardFormTitle": "Contéiner para o formulário de cartão de crédito",
Ok!

2021-01-08 18:39 UTC, wdsrocha requested changes
The branch seems to have few conflicts with master. Could you rebase please?

2021-01-15 18:55 UTC, lucasecdb approved these changes

2021-01-15 19:39 UTC, wdsrocha commented on react/Payment.tsx
> +import React, { useState, useRef, useCallback, useEffect} from 'react'
weird that eslint didn't catch that 🤔
for me, it only catched when I ran prettier on this specific file. anyone knows why?

Anyway, if you feel like fixing it, ok, but not obligatory in my opinion

2021-01-18 17:34 UTC, wdsrocha approved these changes

2021-01-18 18:33 UTC, merged