Add new translations
vtex-apps/checkout-payment pull request #31
Opened 2021-04-21 21:48 UTC by camilavcoutinho

#### What problem is this solving?

Add Finnish, French, Dutch, Norwegian, Romanian, and Slovenian.

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
✔️ | New feature 
_ | Breaking change 
_ | Technical improvements 

#### Notes

2021-04-22 12:57 UTC, dvm1984 approved these changes

2021-04-22 14:23 UTC, lucasecdb requested changes

2021-04-22 14:23 UTC, lucasecdb commented on messages/fr.json
> +  "store/checkout-payment.installmentWithoutValue": "{count}x {hasInterestRate, select, false {without interest} true {avec intérêts de {taux d'interet}% mois}}",
```suggestion
  "store/checkout-payment.installmentWithoutValue": "{count}x {hasInterestRate, select, false {without interest} true {avec intérêts de {interestRate}% mois}}",
```

2021-04-22 14:23 UTC, lucasecdb commented on messages/nl.json
> +  "store/checkout-payment.installmentWithoutValue": "{count}x {hasInterestRate, select, false {without interest} true {met een rente van {Rentepercentage}% per maand}}",
```suggestion
  "store/checkout-payment.installmentWithoutValue": "{count}x {hasInterestRate, select, false {without interest} true {met een rente van {interestRate}% per maand}}",
```

2021-04-26 18:37 UTC, lucasecdb approved these changes

2021-04-26 18:39 UTC, merged